CREATE TABLE IF NOT EXISTS places (
    id UUID PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    category VARCHAR(50) NOT NULL,
    lat DOUBLE PRECISION NOT NULL,
    lng DOUBLE PRECISION NOT NULL,
    rating DOUBLE PRECISION NOT NULL,
    description TEXT NOT NULL,
    open_hours VARCHAR(100) NOT NULL
);
